-- Migración V2: Tablas para Onboarding de Clientes Personas Físicas

CREATE TABLE IF NOT EXISTS clientes (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_clientes PRIMARY KEY,
    primer_nombre         VARCHAR(50)   NOT NULL,
    segundo_nombre        VARCHAR(50),
    apellido_paterno      VARCHAR(50)   NOT NULL,
    apellido_materno      VARCHAR(50)   NOT NULL,
    curp                  CHAR(18)      NOT NULL CONSTRAINT uq_clientes_curp UNIQUE,
    rfc                   VARCHAR(13)   NOT NULL CONSTRAINT uq_clientes_rfc UNIQUE,
    correo                VARCHAR(100)  NOT NULL CONSTRAINT uq_clientes_correo UNIQUE,
    fecha_nacimiento      DATE          NOT NULL,
    telefono_movil        CHAR(10)      NOT NULL,
    telefono_alternativo  CHAR(10),
    sexo                  CHAR(1)       NOT NULL,
    estado_civil          CHAR(1)       NOT NULL,
    nacionalidad          VARCHAR(50)   NOT NULL,
    ocupacion             VARCHAR(50)   NOT NULL,
    empresa               VARCHAR(50)   NOT NULL,
    ingreso_mensual       NUMERIC(12,2) NOT NULL,
    activo                BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_registro        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_baja            TIMESTAMP,
    CONSTRAINT ck_clientes_ingreso_mensual CHECK (ingreso_mensual > 0),
    CONSTRAINT ck_clientes_sexo CHECK (sexo IN ('H', 'M')),
    CONSTRAINT ck_clientes_curp_len CHECK (LENGTH(curp) = 18),
    CONSTRAINT ck_clientes_rfc_len CHECK (LENGTH(rfc) >= 12 AND LENGTH(rfc) <= 13),
    CONSTRAINT ck_clientes_telefono_movil_len CHECK (LENGTH(telefono_movil) = 10),
    CONSTRAINT ck_clientes_telefono_alternativo_len CHECK (telefono_alternativo IS NULL OR LENGTH(telefono_alternativo) = 10),
    CONSTRAINT ck_clientes_estado_civil CHECK (estado_civil IN ('S', 'C', 'D', 'V', 'U'))
);

CREATE TABLE IF NOT EXISTS domicilios (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_domicilios PRIMARY KEY,
    cliente_id            INTEGER       NOT NULL CONSTRAINT uq_domicilios_cliente UNIQUE CONSTRAINT fk_domicilios_cliente REFERENCES clientes(id),
    calle                 VARCHAR(100)  NOT NULL,
    numero_exterior       VARCHAR(20)   NOT NULL,
    numero_interior       VARCHAR(20),
    colonia               VARCHAR(100)  NOT NULL,
    municipio             VARCHAR(100)  NOT NULL,
    estado                VARCHAR(50)   NOT NULL,
    pais                  VARCHAR(50)   NOT NULL,
    codigo_postal         CHAR(5)       NOT NULL,
    CONSTRAINT ck_domicilios_codigo_postal_len CHECK (LENGTH(codigo_postal) = 5)
);

CREATE TABLE IF NOT EXISTS cuentas (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_cuentas PRIMARY KEY,
    cliente_id            INTEGER       NOT NULL CONSTRAINT fk_cuentas_cliente REFERENCES clientes(id),
    numero_cuenta         CHAR(10)      NOT NULL CONSTRAINT uq_cuentas_numero_cuenta UNIQUE,
    saldo                 NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    estatus               CHAR(1)       NOT NULL DEFAULT 'A',
    fecha_creacion        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cuentas_saldo CHECK (saldo >= 0),
    CONSTRAINT ck_cuentas_numero_cuenta_len CHECK (LENGTH(numero_cuenta) = 10),
    CONSTRAINT ck_cuentas_estatus CHECK (estatus IN ('A', 'I'))
);

CREATE TABLE IF NOT EXISTS usuarios (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_usuarios PRIMARY KEY,
    cliente_id            INTEGER       NOT NULL CONSTRAINT uq_usuarios_cliente UNIQUE CONSTRAINT fk_usuarios_cliente REFERENCES clientes(id),
    correo                VARCHAR(100)  NOT NULL CONSTRAINT uq_usuarios_correo UNIQUE,
    password_hash         CHAR(60)      NOT NULL,
    activo                BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_clientes_fecha_registro ON clientes(fecha_registro);
CREATE INDEX IF NOT EXISTS ix_clientes_activo ON clientes(activo);
CREATE INDEX IF NOT EXISTS ix_cuentas_estatus ON cuentas(estatus);
CREATE INDEX IF NOT EXISTS ix_cuentas_cliente_id ON cuentas(cliente_id);
